import { Router } from 'express';
import { requerirAutenticacion } from '../seguridad/autenticacion.middleware.js';
import { requerirPermiso } from '../seguridad/permisos.middleware.js';
import { esquemaAbrirCaja, esquemaAnularVenta, esquemaCerrarCaja, esquemaConsultaVentas, esquemaIdVenta, esquemaVenta } from './ventas.esquemas.js';
import { abrirCaja, anularVenta, cerrarCaja, crearVenta, listarCajasDisponibles, listarVentas, obtenerSesion, obtenerVenta, referenciasVenta, resumenCaja } from './ventas.servicio.js';

export const rutasVentas = Router(); rutasVentas.use(requerirAutenticacion);
rutasVentas.get('/caja/actual', requerirPermiso('caja.abrir'), async (req, res) => res.json({ dato: await obtenerSesion(req.usuario.id) }));
rutasVentas.get('/caja/disponibles', requerirPermiso('caja.abrir'), async (_req, res) => res.json({ datos: await listarCajasDisponibles() }));
rutasVentas.get('/caja/resumen', requerirPermiso('caja.cerrar'), async (req, res) => { const dato = await resumenCaja(req.usuario.id); if (!dato) return res.status(404).json({ mensaje: 'No tenés una caja abierta' }); res.json({ dato }); });
rutasVentas.post('/caja/abrir', requerirPermiso('caja.abrir'), async (req, res) => { const v = esquemaAbrirCaja.safeParse(req.body); if (!v.success) return res.status(400).json({ mensaje: 'Datos de apertura inválidos' }); try { res.status(201).json({ dato: await abrirCaja(req.usuario.id, v.data.caja_id, v.data.monto_inicial) }); } catch (error) { if (['CAJA_ABIERTA', 'CAJA_NO_DISPONIBLE'].includes(error.codigoPublico)) return res.status(409).json({ mensaje: error.message }); throw error; } });
rutasVentas.post('/caja/cerrar', requerirPermiso('caja.cerrar'), async (req, res) => { const v = esquemaCerrarCaja.safeParse(req.body); if (!v.success) return res.status(400).json({ mensaje: 'Monto contado inválido' }); try { res.json({ dato: await cerrarCaja(req.usuario.id, v.data.monto_contado) }); } catch (error) { if (error.codigoPublico === 'SIN_CAJA') return res.status(409).json({ mensaje: error.message }); throw error; } });
rutasVentas.get('/referencias', requerirPermiso('ventas.crear'), async (_req, res) => res.json({ datos: await referenciasVenta() }));
rutasVentas.get('/historial', requerirPermiso('ventas.crear'), async (req, res) => { const v = esquemaConsultaVentas.safeParse(req.query); if (!v.success) return res.status(400).json({ mensaje: 'Consulta inválida' }); const veTodas = req.usuario.roles.some((rol) => ['administrador', 'supervisor'].includes(rol)); res.json(await listarVentas(v.data, veTodas ? null : req.usuario.id)); });
rutasVentas.get('/historial/:id', requerirPermiso('ventas.crear'), async (req, res) => { const id = esquemaIdVenta.safeParse(req.params.id); if (!id.success) return res.status(400).json({ mensaje: 'Venta inválida' }); const veTodas = req.usuario.roles.some((rol) => ['administrador', 'supervisor'].includes(rol)); const dato = await obtenerVenta(id.data, veTodas ? null : req.usuario.id); if (!dato) return res.status(404).json({ mensaje: 'No se encontró la venta' }); res.json({ dato }); });
rutasVentas.post('/:id/anular', requerirPermiso('ventas.anular'), async (req, res) => { const id = esquemaIdVenta.safeParse(req.params.id); const datos = esquemaAnularVenta.safeParse(req.body); if (!id.success || !datos.success) return res.status(400).json({ mensaje: 'Motivo de anulación inválido' }); try { res.json({ dato: await anularVenta(id.data, req.usuario.id, datos.data.motivo) }); } catch (error) { if (error.codigoPublico === 'NO_ENCONTRADA') return res.status(404).json({ mensaje: error.message }); if (error.codigoPublico) return res.status(409).json({ mensaje: error.message }); throw error; } });
rutasVentas.post('/', requerirPermiso('ventas.crear'), async (req, res) => { const v = esquemaVenta.safeParse(req.body); if (!v.success) return res.status(400).json({ mensaje: 'Datos de venta inválidos' }); try { res.status(201).json({ dato: await crearVenta(req.usuario.id, v.data) }); } catch (error) { if (error.codigoPublico) return res.status(409).json({ mensaje: error.message }); throw error; } });
