import assert from 'node:assert/strict';import test from 'node:test';import { esquemaAdelanto,esquemaEmpleado,esquemaLiquidacion,esquemaPagoSueldo } from '../src/modulos/empleados/empleados.esquemas.js';import { esquemaCuenta,esquemaMovimiento,esquemaTransferencia } from '../src/modulos/tesoreria/tesoreria.esquemas.js';
import { esquemaAbrirCaja, esquemaCaja, esquemaCerrarCaja, esquemaRendirCaja } from '../src/modulos/ventas/ventas.esquemas.js';
test('valida modalidades y datos laborales del empleado',()=>{const d={nombres:'Ana',apellidos:'Pérez',modalidad_pago:'quincenal',sueldo_base:300000,fecha_ingreso:'2026-08-01',esta_activo:true};assert.equal(esquemaEmpleado.safeParse(d).success,true);assert.equal(esquemaEmpleado.safeParse({...d,modalidad_pago:'cada_dos_meses'}).success,false)});
test('valida adelantos y períodos de liquidación',()=>{assert.equal(esquemaAdelanto.safeParse({fecha:'2026-08-04',monto:10000,medio:'efectivo',origen_efectivo:'caja'}).success,true);assert.equal(esquemaAdelanto.safeParse({fecha:'2026-08-04',monto:10000,medio:'transferencia'}).success,false);assert.equal(esquemaAdelanto.safeParse({fecha:'2026-08-04',monto:10000,medio:'transferencia',cuenta_tesoreria_id:1}).success,true);assert.equal(esquemaPagoSueldo.safeParse({monto:50000,medio:'efectivo',origen_efectivo:'tesoreria',cuenta_tesoreria_id:1}).success,true);assert.equal(esquemaLiquidacion.safeParse({empleado_id:1,periodo_desde:'2026-08-15',periodo_hasta:'2026-08-01',sueldo_base:100000}).success,false)});
test('valida cuentas y movimientos de tesorería',()=>{assert.equal(esquemaCuenta.safeParse({nombre:'Banco',tipo:'banco',moneda:'ARS',saldo_inicial:0}).success,true);assert.equal(esquemaMovimiento.safeParse({cuenta_tesoreria_id:1,tipo:'egreso',categoria:'sueldo',concepto:'Pago de nómina',monto:1,fecha:'2026-08-04'}).success,true)});
test('una transferencia requiere cuentas diferentes',()=>{const d={cuenta_origen_id:1,cuenta_destino_id:1,monto:100,concepto:'Traspaso',fecha:'2026-08-04'};assert.equal(esquemaTransferencia.safeParse(d).success,false);assert.equal(esquemaTransferencia.safeParse({...d,cuenta_destino_id:2}).success,true)});
test('valida el código y nombre de una caja',()=>{assert.equal(esquemaCaja.safeParse({codigo:'CAJA_3',nombre:'Caja 3',esta_activa:true}).success,true);assert.equal(esquemaCaja.safeParse({codigo:'Caja con espacios',nombre:'Caja 3',esta_activa:true}).success,false)});
test('una apertura con fondo exige una cuenta de efectivo de origen',()=>{assert.equal(esquemaAbrirCaja.safeParse({caja_id:1,monto_inicial:80000}).success,false);assert.equal(esquemaAbrirCaja.safeParse({caja_id:1,monto_inicial:80000,cuenta_origen_id:1}).success,true);assert.equal(esquemaAbrirCaja.safeParse({caja_id:1,monto_inicial:0}).success,true)});
test('valida cierre inmediato o pendiente y rendición posterior',()=>{assert.equal(esquemaCerrarCaja.safeParse({monto_contado:89210,cuenta_destino_id:1}).success,true);assert.equal(esquemaCerrarCaja.safeParse({monto_contado:89210,cuenta_destino_id:null}).success,true);assert.equal(esquemaRendirCaja.safeParse({cuenta_destino_id:1}).success,true);assert.equal(esquemaRendirCaja.safeParse({cuenta_destino_id:0}).success,false)});
