import { Router } from 'express';
import { requerirAutenticacion } from '../seguridad/autenticacion.middleware.js';
import { requerirPermiso } from '../seguridad/permisos.middleware.js';
import { esquemaConsultaCompras, esquemaCrearCompra, esquemaEditarCompra, esquemaIdCompra, esquemaRecibirCompra } from './compras.esquemas.js';
import { cambiarEstadoCompra, crearCompra, editarCompra, listarCompras, obtenerCompra, recibirCompra, referenciasCompras } from './compras.servicio.js';

export const rutasCompras = Router(); rutasCompras.use(requerirAutenticacion);
rutasCompras.get('/', requerirPermiso('compras.ver'), async (req, res) => { const v = esquemaConsultaCompras.safeParse(req.query); if (!v.success) return res.status(400).json({ mensaje: 'Consulta inválida' }); res.json(await listarCompras(v.data)); });
rutasCompras.get('/referencias', requerirPermiso('compras.ver'), async (_req, res) => res.json(await referenciasCompras()));
rutasCompras.get('/:id', requerirPermiso('compras.ver'), async (req, res) => { const id = esquemaIdCompra.safeParse(req.params.id); if (!id.success) return res.status(400).json({ mensaje: 'Compra inválida' }); const dato = await obtenerCompra(id.data); if (!dato) return res.status(404).json({ mensaje: 'No se encontró la compra' }); res.json({ dato }); });
rutasCompras.post('/', requerirPermiso('compras.gestionar'), async (req, res) => { const v = esquemaCrearCompra.safeParse(req.body); if (!v.success) return res.status(400).json({ mensaje: 'Datos de compra inválidos', errores: v.error.flatten() }); res.status(201).json({ dato: await crearCompra(v.data, req.usuario.id) }); });
rutasCompras.put('/:id', requerirPermiso('compras.gestionar'), async (req, res) => { const id = esquemaIdCompra.safeParse(req.params.id); const datos = esquemaEditarCompra.safeParse(req.body); if (!id.success || !datos.success) return res.status(400).json({ mensaje: 'Datos de compra inválidos' }); try { res.json({ dato: await editarCompra(id.data, datos.data) }); } catch (error) { if (error.codigoPublico === 'NO_ENCONTRADA') return res.status(404).json({ mensaje: error.message }); if (error.codigoPublico === 'ESTADO_INVALIDO') return res.status(409).json({ mensaje: error.message }); throw error; } });
rutasCompras.post('/:id/recibir', requerirPermiso('compras.gestionar'), async (req, res) => { const id = esquemaIdCompra.safeParse(req.params.id); const datos = esquemaRecibirCompra.safeParse(req.body); if (!id.success || !datos.success) return res.status(400).json({ mensaje: 'Datos de recepción inválidos' }); try { res.json({ dato: await recibirCompra(id.data, req.usuario.id, datos.data) }); } catch (error) { if (error.codigoPublico === 'NO_ENCONTRADA') return res.status(404).json({ mensaje: error.message }); if (error.codigoPublico) return res.status(409).json({ mensaje: error.message }); throw error; } });
rutasCompras.post('/:id/enviar', requerirPermiso('compras.gestionar'), async (req, res) => { const id = esquemaIdCompra.safeParse(req.params.id); if (!id.success) return res.status(400).json({ mensaje: 'Compra inválida' }); try { res.json({ dato: await cambiarEstadoCompra(id.data, 'enviar') }); } catch (error) { return res.status(409).json({ mensaje: error.message }); } });
rutasCompras.post('/:id/cancelar', requerirPermiso('compras.gestionar'), async (req, res) => { const id = esquemaIdCompra.safeParse(req.params.id); if (!id.success) return res.status(400).json({ mensaje: 'Compra inválida' }); try { res.json({ dato: await cambiarEstadoCompra(id.data, 'cancelar') }); } catch (error) { return res.status(409).json({ mensaje: error.message }); } });
