import { useCallback, useEffect, useState } from 'react';
import { Modal } from './componentes/Modal.jsx';

async function pedir(ruta, token, opciones = {}) { const respuesta = await fetch(ruta, { ...opciones, headers: { Authorization: `Bearer ${token}`, ...(opciones.body ? { 'Content-Type': 'application/json' } : {}) } }); const datos = await respuesta.json(); if (!respuesta.ok) throw new Error(datos.mensaje || 'No se pudo completar la operación'); return datos; }
function Formulario({ cliente, alGuardar, alCancelar }) { return <form className="formulario-modal" onSubmit={alGuardar}><div className="campos-producto"><div className="campo campo--ancho"><label>Nombre y apellido / Razón social</label><input name="nombre" defaultValue={cliente?.nombre || ''} minLength="2" maxLength="160" required autoFocus /></div><div className="campo"><label>Tipo de documento</label><select name="tipo_documento" defaultValue={cliente?.tipo_documento || ''}><option value="">Sin especificar</option><option>DNI</option><option>CUIT</option><option>CUIL</option><option>OTRO</option></select></div><div className="campo"><label>Número</label><input name="numero_documento" defaultValue={cliente?.numero_documento || ''} maxLength="20" /></div><div className="campo"><label>Teléfono</label><input name="telefono" defaultValue={cliente?.telefono || ''} maxLength="30" /></div><div className="campo"><label>Correo electrónico</label><input name="correo_electronico" type="email" defaultValue={cliente?.correo_electronico || ''} maxLength="254" /></div><div className="campo campo--ancho"><label>Dirección</label><input name="direccion" defaultValue={cliente?.direccion || ''} maxLength="255" /></div><div className="campo campo--ancho"><label>Observaciones</label><textarea name="observaciones" defaultValue={cliente?.observaciones || ''} maxLength="500" rows="3" /></div>{cliente && <label className="filtro-verificacion campo--ancho"><input name="esta_activo" type="checkbox" defaultChecked={Boolean(cliente.esta_activo)} /> Cliente activo</label>}</div><div className="modal__acciones"><button type="button" className="boton boton--secundario" onClick={alCancelar}>Cancelar</button><button className="boton">{cliente ? 'Guardar cambios' : 'Crear cliente'}</button></div></form>; }
export function Clientes({ token, permisos }) {
  const [clientes, setClientes] = useState([]); const [total, setTotal] = useState(0); const [pagina, setPagina] = useState(1); const [texto, setTexto] = useState(''); const [buscar, setBuscar] = useState(''); const [estado, setEstado] = useState('activos'); const [editado, setEditado] = useState(undefined); const [modal, setModal] = useState(false); const [mensaje, setMensaje] = useState(''); const limite = 25;
  const cargar = useCallback(async () => { try { const parametros = new URLSearchParams({ pagina, limite, estado }); if (buscar) parametros.set('buscar', buscar); const respuesta = await pedir(`/api/clientes?${parametros}`, token); setClientes(respuesta.datos); setTotal(respuesta.total); } catch (error) { setMensaje(error.message); } }, [token, pagina, buscar, estado]);
  useEffect(() => { cargar(); }, [cargar]); useEffect(() => { const t = setTimeout(() => { setPagina(1); setBuscar(texto.trim()); }, 300); return () => clearTimeout(t); }, [texto]);
  async function guardar(evento) { evento.preventDefault(); const f = new FormData(evento.currentTarget); const opt = (nombre) => f.get(nombre) || null; const datos = { nombre: f.get('nombre'), tipo_documento: opt('tipo_documento'), numero_documento: opt('numero_documento'), telefono: opt('telefono'), correo_electronico: opt('correo_electronico'), direccion: opt('direccion'), observaciones: opt('observaciones'), ...(editado ? { esta_activo: f.get('esta_activo') === 'on' } : {}) }; try { await pedir(editado ? `/api/clientes/${editado.id}` : '/api/clientes', token, { method: editado ? 'PUT' : 'POST', body: JSON.stringify(datos) }); setModal(false); setEditado(undefined); setMensaje(editado ? 'Cliente actualizado correctamente.' : 'Cliente creado correctamente.'); await cargar(); } catch (error) { setMensaje(error.message); } }
  const gestionar = permisos.includes('clientes.gestionar'); const paginas = Math.max(1, Math.ceil(total / limite)); const cerrar = () => { setModal(false); setEditado(undefined); };
  return <section className="modulo"><div className="modulo__encabezado"><div><p className="etiqueta">GESTIÓN COMERCIAL</p><h2>Clientes</h2></div>{gestionar && <button className="boton" onClick={() => setModal(true)}>Nuevo cliente</button>}</div><div className="barra-filtros"><input value={texto} onChange={(e) => setTexto(e.target.value)} placeholder="Buscar por nombre, documento, teléfono o correo" /><select value={estado} onChange={(e) => { setEstado(e.target.value); setPagina(1); }}><option value="activos">Activos</option><option value="inactivos">Inactivos</option><option value="todos">Todos</option></select></div><p className="filtro-activo">Mostrando {total.toLocaleString('es-AR')} clientes{buscar ? ` para “${buscar}”` : ''}.</p>{mensaje && <p className="mensaje">{mensaje}</p>}<article className="panel"><div className="panel__encabezado"><h3>Padrón de clientes</h3><span>Página {pagina} de {paginas}</span></div>{clientes.length ? <div className="tabla-contenedor"><table><thead><tr><th>Cliente</th><th>Documento</th><th>Teléfono</th><th>Correo</th><th>Estado</th>{gestionar && <th></th>}</tr></thead><tbody>{clientes.map((cliente) => <tr key={cliente.id}><td>{cliente.nombre}</td><td>{cliente.numero_documento ? `${cliente.tipo_documento || ''} ${cliente.numero_documento}` : '—'}</td><td>{cliente.telefono || '—'}</td><td>{cliente.correo_electronico || '—'}</td><td><span className={cliente.esta_activo ? 'estado-activo' : 'estado-inactivo'}>{cliente.esta_activo ? 'Activo' : 'Inactivo'}</span></td>{gestionar && <td><button className="boton-tabla" onClick={() => { setEditado(cliente); setModal(true); }}>Editar</button></td>}</tr>)}</tbody></table></div> : <p className="vacio">Todavía no hay clientes para mostrar.</p>}<div className="paginacion"><button disabled={pagina === 1} onClick={() => setPagina((v) => v - 1)}>Anterior</button><button disabled={pagina >= paginas} onClick={() => setPagina((v) => v + 1)}>Siguiente</button></div></article><Modal abierto={modal} titulo={editado ? 'Editar cliente' : 'Nuevo cliente'} ancho="grande" alCerrar={cerrar}><Formulario key={editado?.id || 'nuevo'} cliente={editado} alGuardar={guardar} alCancelar={cerrar} /></Modal></section>;
}
