import { useCallback, useEffect, useState } from 'react';
import { Modal } from './componentes/Modal.jsx';

async function pedir(ruta, token, opciones = {}) { const r = await fetch(ruta, { ...opciones, headers: { Authorization: `Bearer ${token}`, ...(opciones.body ? { 'Content-Type': 'application/json' } : {}) } }); const d = await r.json(); if (!r.ok) throw new Error(d.mensaje || 'No se pudo completar la operación'); return d; }

export function Compras({ token, permisos }) {
  const [compras,setCompras]=useState([]); const [total,setTotal]=useState(0); const [pagina,setPagina]=useState(1); const [estado,setEstado]=useState('todos'); const [texto,setTexto]=useState(''); const [buscar,setBuscar]=useState(''); const [refs,setRefs]=useState({proveedores:[],productos:[]}); const [modal,setModal]=useState(false); const [items,setItems]=useState([{producto_id:'',cantidad:1,costo_unitario:0}]); const [mensaje,setMensaje]=useState(''); const limite=25;
  const cargar=useCallback(async()=>{try{const p=new URLSearchParams({pagina:String(pagina),limite:String(limite),estado});if(buscar)p.set('buscar',buscar);const [c,r]=await Promise.all([pedir(`/api/compras?${p}`,token),pedir('/api/compras/referencias',token)]);setCompras(c.datos);setTotal(c.total);setRefs(r);}catch(e){setMensaje(e.message)}},[token,pagina,estado,buscar]);
  useEffect(()=>{cargar()},[cargar]); useEffect(()=>{const t=setTimeout(()=>{setPagina(1);setBuscar(texto.trim())},300);return()=>clearTimeout(t)},[texto]);
  function cambiar(i,campo,valor){setItems(actual=>actual.map((item,j)=>j===i?{...item,[campo]:valor}:item))}
  function elegir(i,id){const producto=refs.productos.find(p=>String(p.id)===id);setItems(actual=>actual.map((item,j)=>j===i?{...item,producto_id:id,costo_unitario:Number(producto?.precio_costo||0)}:item))}
  async function guardar(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await pedir('/api/compras',token,{method:'POST',body:JSON.stringify({proveedor_id:Number(f.get('proveedor_id')),fecha_esperada:f.get('fecha_esperada')||null,observaciones:f.get('observaciones')||null,detalles:items.map(i=>({producto_id:Number(i.producto_id),cantidad:Number(i.cantidad),costo_unitario:Number(i.costo_unitario)}))})});setModal(false);setItems([{producto_id:'',cantidad:1,costo_unitario:0}]);setMensaje('Orden de compra creada como borrador.');await cargar()}catch(error){setMensaje(error.message)}}
  async function recibir(compra){if(!window.confirm(`¿Confirmar la recepción de la compra #${compra.id}? El stock aumentará automáticamente.`))return;try{const r=await pedir(`/api/compras/${compra.id}/recibir`,token,{method:'POST'});setMensaje(`${r.dato.productos_recibidos} productos ingresaron al stock.`);await cargar()}catch(error){setMensaje(error.message)}}
  const paginas=Math.max(1,Math.ceil(total/limite)); const totalOrden=items.reduce((s,i)=>s+Number(i.cantidad||0)*Number(i.costo_unitario||0),0);
  return <section className="modulo"><div className="modulo__encabezado"><div><p className="etiqueta">COMPRAS</p><h2>Órdenes de compra</h2></div>{permisos.includes('compras.gestionar')&&<button className="boton" onClick={()=>setModal(true)}>Nueva orden</button>}</div>
    <div className="barra-filtros"><input value={texto} onChange={e=>setTexto(e.target.value)} placeholder="Buscar por número o proveedor"/><select value={estado} onChange={e=>{setEstado(e.target.value);setPagina(1)}}><option value="todos">Todos los estados</option><option value="borrador">Borradores</option><option value="enviada">Enviadas</option><option value="recibida">Recibidas</option><option value="cancelada">Canceladas</option></select></div><p className="filtro-activo">Mostrando {total} órdenes.</p>{mensaje&&<p className="mensaje">{mensaje}</p>}
    <article className="panel"><div className="panel__encabezado"><h3>Compras</h3><span>Página {pagina} de {paginas}</span></div>{compras.length?<div className="tabla-contenedor"><table><thead><tr><th>Número</th><th>Fecha</th><th>Proveedor</th><th>Productos</th><th>Total</th><th>Estado</th><th></th></tr></thead><tbody>{compras.map(c=><tr key={c.id}><td>#{c.id}</td><td>{new Date(c.fecha_creacion).toLocaleDateString('es-AR')}</td><td>{c.proveedor}</td><td>{c.productos}</td><td>${Number(c.total).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td><span className="estado-activo">{c.estado}</span></td><td>{['borrador','enviada'].includes(c.estado)&&permisos.includes('compras.gestionar')&&<button className="boton-tabla" onClick={()=>recibir(c)}>Recibir</button>}</td></tr>)}</tbody></table></div>:<p className="vacio">Todavía no hay órdenes de compra.</p>}<div className="paginacion"><button disabled={pagina===1} onClick={()=>setPagina(p=>p-1)}>Anterior</button><button disabled={pagina>=paginas} onClick={()=>setPagina(p=>p+1)}>Siguiente</button></div></article>
    <Modal abierto={modal} titulo="Nueva orden de compra" ancho="grande" alCerrar={()=>setModal(false)}><form className="formulario-modal" onSubmit={guardar}><div className="campos-producto"><div className="campo"><label>Proveedor</label><select name="proveedor_id" required defaultValue=""><option value="" disabled>Seleccionar</option>{refs.proveedores.map(p=><option key={p.id} value={p.id}>{p.nombre_fantasia||p.razon_social}</option>)}</select></div><div className="campo"><label>Entrega esperada</label><input name="fecha_esperada" type="date"/></div></div><div className="tabla-contenedor"><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Costo unitario</th><th></th></tr></thead><tbody>{items.map((item,i)=><tr key={i}><td><select value={item.producto_id} onChange={e=>elegir(i,e.target.value)} required><option value="">Seleccionar producto</option>{refs.productos.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></td><td><input type="number" min="0.001" step="0.001" value={item.cantidad} onChange={e=>cambiar(i,'cantidad',e.target.value)} required/></td><td><input type="number" min="0" step="0.01" value={item.costo_unitario} onChange={e=>cambiar(i,'costo_unitario',e.target.value)} required/></td><td><button type="button" className="boton-tabla" disabled={items.length===1} onClick={()=>setItems(a=>a.filter((_,j)=>j!==i))}>Quitar</button></td></tr>)}</tbody></table></div><button type="button" className="boton boton--secundario" onClick={()=>setItems(a=>[...a,{producto_id:'',cantidad:1,costo_unitario:0}])}>Agregar producto</button><div><label>Observaciones</label><textarea name="observaciones" maxLength="500" rows="2"/></div><p>Total estimado: <strong>${totalOrden.toLocaleString('es-AR',{minimumFractionDigits:2})}</strong></p><div className="modal__acciones"><button type="button" className="boton boton--secundario" onClick={()=>setModal(false)}>Cancelar</button><button className="boton">Crear borrador</button></div></form></Modal></section>;
}
