import { useEffect, useState } from 'react';
import { Modal } from './componentes/Modal.jsx';
import { ConfiguracionEcommerce } from './componentes/ConfiguracionEcommerce.jsx';

const dinero=(n)=>Number(n||0).toLocaleString('es-AR',{style:'currency',currency:'ARS'});
const fecha=(v)=>v?new Date(v).toLocaleString('es-AR',{hour12:false}):'—';
export function Ecommerce({token,permisos}){
 const [vista,setVista]=useState('pedidos'),[datos,setDatos]=useState([]),[total,setTotal]=useState(0),[buscar,setBuscar]=useState(''),[filtro,setFiltro]=useState(''),[detalle,setDetalle]=useState(null),[mensaje,setMensaje]=useState(''),[config,setConfig]=useState(null),[cuentas,setCuentas]=useState([]),[cobrando,setCobrando]=useState(false),[promo,setPromo]=useState(false);
 const api=async(r,o={})=>{const x=await fetch(`/api/ecommerce/admin${r}`,{...o,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}}),d=await x.json();if(!x.ok)throw Error(d.mensaje);return d};
 const cargar=async()=>{try{if(vista==='configuracion'){setConfig((await api('/configuracion')).dato);return}if(vista==='promociones'){const d=await api('/promociones');setDatos(d.datos);setTotal(d.datos.length);return}const r=vista==='productos'?`/productos?buscar=${encodeURIComponent(buscar)}&estado=${filtro||'todos'}&limite=50`:`/pedidos?buscar=${encodeURIComponent(buscar)}&estado=${filtro}&limite=50`,d=await api(r);setDatos(d.datos);setTotal(d.total)}catch(e){setMensaje(e.message)}};
 // La recarga depende exclusivamente de los filtros visibles; `cargar` se redefine al renderizar.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{const t=setTimeout(cargar,200);return()=>clearTimeout(t)},[vista,buscar,filtro]);
 const ver=async(id)=>{setDetalle((await api(`/pedidos/${id}`)).dato);const r=await fetch('/api/tesoreria/cuentas',{headers:{Authorization:`Bearer ${token}`}});if(r.ok)setCuentas((await r.json()).datos||[])};
 const avanzar=async(estado)=>{try{await api(`/pedidos/${detalle.id}/estado`,{method:'PUT',body:JSON.stringify({estado})});await ver(detalle.id);cargar()}catch(e){setMensaje(e.message)}};
 const preparar=async()=>{await api(`/pedidos/${detalle.id}/preparacion`,{method:'PUT',body:JSON.stringify({items:detalle.detalles.map(d=>({detalle_id:d.id,cantidad_confirmada:Number(d.cantidad_solicitada),producto_sustituto_id:null,observaciones:''}))})});await ver(detalle.id);cargar()};
 const cobrar=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/pedidos/${detalle.id}/pagos`,{method:'POST',body:JSON.stringify({proveedor:f.get('proveedor'),monto_bruto:Number(f.get('monto')),comision:Number(f.get('comision')),referencia_externa:f.get('referencia'),cuenta_tesoreria_id:Number(f.get('cuenta')),idempotencia:`manual-${detalle.id}-${Date.now()}`})});setCobrando(false);await ver(detalle.id);cargar()}catch(x){setMensaje(x.message)}};
 const publicar=async(p)=>{await api(`/productos/${p.id}`,{method:'PUT',body:JSON.stringify({esta_publicado:!p.esta_publicado,nombre_online:null,descripcion_online:null,precio_online:null,stock_seguridad:Number(p.stock_seguridad),cantidad_maxima_pedido:p.cantidad_maxima_pedido?Number(p.cantidad_maxima_pedido):null,permite_sustitucion:Boolean(p.permite_sustitucion),permite_retiro:Boolean(p.permite_retiro),permite_envio:Boolean(p.permite_envio),es_destacado:Boolean(p.es_destacado),orden_destacado:Number(p.orden_destacado||0),imagenes:[]})});cargar()};
 const guardar=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget),c=config.configuracion,n=(k)=>Number(f.get(k)),b=(k)=>f.get(k)==='on';try{await api('/configuracion',{method:'PUT',body:JSON.stringify({nombre_tienda:f.get('nombre_tienda'),esta_activa:b('esta_activa'),direccion_origen:f.get('direccion_origen'),latitud_origen:f.get('latitud_origen')?n('latitud_origen'):null,longitud_origen:f.get('longitud_origen')?n('longitud_origen'):null,distancia_maxima_km:n('distancia_maxima_km'),pedido_minimo:n('pedido_minimo'),envio_gratis_desde:f.get('envio_gratis_desde')?n('envio_gratis_desde'):null,costo_envio_base:n('costo_envio_base'),costo_por_km:n('costo_por_km'),minutos_reserva:n('minutos_reserva'),permite_retiro:b('permite_retiro'),permite_envio:b('permite_envio'),permite_efectivo:b('permite_efectivo'),permite_transferencia:b('permite_transferencia'),permite_mercado_pago:b('permite_mercado_pago'),cuenta_mercado_pago_id:c.cuenta_mercado_pago_id,telefono_contacto:f.get('telefono_contacto'),mensaje_portada:f.get('mensaje_portada')})});setMensaje('Configuración guardada');cargar()}catch(x){setMensaje(x.message)}};
 const guardarPromo=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget),tipo=f.get('tipo'),valor=Number(f.get('valor'));try{await api('/promociones',{method:'POST',body:JSON.stringify({nombre:f.get('nombre'),descripcion:f.get('descripcion'),tipo,ambito:tipo==='envio_gratis'?'envio':'pedido',porcentaje:tipo.includes('porcentaje')?valor:null,precio_fijo:tipo.includes('fijo')?valor:null,codigo_cupon:f.get('codigo'),monto_minimo:Number(f.get('minimo')),descuento_maximo:null,fecha_desde:new Date(f.get('desde')).toISOString(),fecha_hasta:new Date(f.get('hasta')).toISOString(),es_acumulable:false,es_destacada:f.get('destacada')==='on',esta_activa:true,productos:[]})});setPromo(false);cargar()}catch(x){setMensaje(x.message)}};
 return <section className="ecommerce-admin"><div className="encabezado-pagina"><div><p className="etiqueta">CANAL ONLINE</p><h1>E-commerce</h1></div><a className="boton boton--secundario" href="/tienda" target="_blank">Ver tienda</a></div><div className="selector-vista ecommerce-vistas">{['pedidos','productos','promociones',...(permisos.includes('ecommerce.gestionar')?['configuracion']:[])].map(v=><button className={vista===v?'activo':''} onClick={()=>{setVista(v);setFiltro('')}} key={v}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div>{mensaje&&<p className="mensaje-informativo">{mensaje}</p>}
 {vista!=='configuracion'&&<div className="barra-filtros ecommerce-filtros"><input placeholder="Buscar…" value={buscar} onChange={e=>setBuscar(e.target.value)}/>{!['promociones'].includes(vista)&&<select value={filtro} onChange={e=>setFiltro(e.target.value)}><option value="">Todos</option>{vista==='productos'?<><option value="publicados">Publicados</option><option value="ocultos">Ocultos</option></>:['pendiente_pago','confirmado','en_preparacion','listo','en_reparto','entregado','cancelado'].map(x=><option key={x}>{x}</option>)}</select>}<span>{total} registros</span></div>}
 {vista==='pedidos'&&<div className="tabla-contenedor"><table><thead><tr><th>Pedido</th><th>Fecha</th><th>Cliente</th><th>Entrega</th><th>Pago</th><th>Total</th><th>Estado</th><th/></tr></thead><tbody>{datos.map(p=><tr key={p.id}><td>#{p.codigo}</td><td>{fecha(p.fecha_creacion)}</td><td>{p.nombre_cliente}</td><td>{p.modalidad_entrega}</td><td>{p.estado_pago}</td><td>{dinero(p.total)}</td><td>{p.estado}</td><td><button className="boton-tabla" onClick={()=>ver(p.id)}>Ver</button></td></tr>)}</tbody></table></div>}
 {vista==='productos'&&<div className="tabla-contenedor"><table><thead><tr><th>Producto</th><th>Categoría</th><th>Precio</th><th>Disponible</th><th/></tr></thead><tbody>{datos.map(p=><tr key={p.id}><td>{p.nombre}</td><td>{p.categoria}</td><td>{dinero(p.precio)}</td><td>{Number(p.disponible_online)}</td><td><button className="boton-tabla" disabled={!permisos.includes('ecommerce.gestionar')} onClick={()=>publicar(p)}>{p.esta_publicado?'Ocultar':'Publicar'}</button></td></tr>)}</tbody></table></div>}
 {vista==='promociones'&&<div><button className="boton" onClick={()=>setPromo(true)}>Nueva promoción</button><div className="tabla-contenedor"><table><thead><tr><th>Nombre</th><th>Tipo</th><th>Ámbito</th><th>Desde</th><th>Hasta</th><th>Estado</th></tr></thead><tbody>{datos.map(p=><tr key={p.id}><td>{p.nombre}</td><td>{p.tipo}</td><td>{p.ambito}</td><td>{fecha(p.fecha_desde)}</td><td>{fecha(p.fecha_hasta)}</td><td>{p.esta_activa?'Activa':'Inactiva'}</td></tr>)}</tbody></table></div></div>}
 {vista==='configuracion'&&config&&<ConfiguracionEcommerce datos={config} alGuardar={guardar}/>}
 {detalle&&<Modal abierto ancho="grande" titulo={`Pedido #${detalle.codigo}`} alCerrar={()=>setDetalle(null)}><p><strong>{detalle.nombre_cliente}</strong> · {detalle.telefono_cliente} · {detalle.correo_cliente}</p><p>{detalle.modalidad_entrega} · {detalle.medio_pago} · Pago: {detalle.estado_pago}</p><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Subtotal</th></tr></thead><tbody>{detalle.detalles.map(d=><tr key={d.id}><td>{d.nombre_sustituto||d.nombre_producto}</td><td>{Number(d.cantidad_confirmada??d.cantidad_solicitada)}</td><td>{dinero(d.subtotal)}</td></tr>)}</tbody></table><p><strong>Total {dinero(detalle.total)}</strong></p>{cobrando&&<form className="formulario formulario--grilla" onSubmit={cobrar}><label>Medio<select name="proveedor" defaultValue={detalle.medio_pago}><option value="efectivo">Efectivo</option><option value="transferencia">Transferencia</option><option value="mercado_pago">Mercado Pago</option></select></label><label>Cuenta<select name="cuenta" required>{cuentas.map(c=><option key={c.id} value={c.id}>{c.nombre} · {dinero(c.saldo)}</option>)}</select></label><label>Importe<input name="monto" type="number" step="0.01" defaultValue={detalle.total} required/></label><label>Comisión<input name="comision" type="number" step="0.01" defaultValue="0"/></label><label>Referencia<input name="referencia" defaultValue={detalle.codigo}/></label><button className="boton">Registrar cobro</button></form>}<div className="acciones-modal">{detalle.estado_pago!=='aprobado'&&permisos.includes('ecommerce.pagos')&&<button onClick={()=>setCobrando(!cobrando)}>Registrar pago</button>}{detalle.estado==='pendiente_pago'&&<button onClick={()=>avanzar('confirmado')}>Confirmar</button>}{detalle.estado==='confirmado'&&<button onClick={()=>avanzar('en_preparacion')}>Preparar</button>}{detalle.estado==='en_preparacion'&&<button onClick={preparar}>Preparación completa</button>}{detalle.estado==='listo'&&detalle.modalidad_entrega==='envio'&&<button onClick={()=>avanzar('en_reparto')}>Enviar</button>}{['listo','en_reparto'].includes(detalle.estado)&&detalle.estado_pago==='aprobado'&&<button className="boton" onClick={async()=>{await api(`/pedidos/${detalle.id}/entrega`,{method:'POST'});setDetalle(null);cargar()}}>Entregar y registrar venta</button>}{!['entregado','cancelado'].includes(detalle.estado)&&<button onClick={()=>avanzar('cancelado')}>Cancelar</button>}</div></Modal>}
 {promo&&<Modal abierto titulo="Nueva promoción" alCerrar={()=>setPromo(false)}><form className="formulario formulario--grilla" onSubmit={guardarPromo}><label>Nombre<input name="nombre" required/></label><label>Tipo<select name="tipo"><option value="porcentaje">Porcentaje sobre pedido</option><option value="cupon_porcentaje">Cupón porcentual</option><option value="cupon_fijo">Cupón de importe fijo</option><option value="envio_gratis">Envío gratis</option></select></label><label>Valor<input name="valor" type="number" step="0.01" defaultValue="10"/></label><label>Monto mínimo<input name="minimo" type="number" step="0.01" defaultValue="0"/></label><label>Código de cupón<input name="codigo"/></label><label>Desde<input name="desde" type="datetime-local" required/></label><label>Hasta<input name="hasta" type="datetime-local" required/></label><label>Descripción<textarea name="descripcion"/></label><label className="fila-check"><input name="destacada" type="checkbox"/> Mostrar como destacada</label><button className="boton">Crear promoción</button></form></Modal>}
 </section>;
}
