import { useCallback, useEffect, useMemo, useState } from 'react';
import { Modal } from './componentes/Modal.jsx';

async function pedir(ruta, token, opciones = {}) { const respuesta = await fetch(ruta, { ...opciones, headers: { Authorization: `Bearer ${token}`, ...(opciones.body ? { 'Content-Type': 'application/json' } : {}) } }); const datos = await respuesta.json(); if (!respuesta.ok) throw new Error(datos.mensaje || 'No se pudo completar la operación'); return datos; }

export function Ventas({ token }) {
  const [sesion, setSesion] = useState(undefined); const [productos, setProductos] = useState([]);
  const [cajasDisponibles, setCajasDisponibles] = useState([]);
  const [buscar, setBuscar] = useState(''); const [carrito, setCarrito] = useState([]);
  const [modalCaja, setModalCaja] = useState(false); const [modalCobro, setModalCobro] = useState(false);
  const [medio, setMedio] = useState('efectivo'); const [recibido, setRecibido] = useState('');
  const [procesando, setProcesando] = useState(false); const [mensaje, setMensaje] = useState('');

  const cargar = useCallback(async () => { try { const [caja, disponibles, referencias] = await Promise.all([pedir('/api/ventas/caja/actual', token), pedir('/api/ventas/caja/disponibles', token), pedir('/api/ventas/referencias', token)]); setSesion(caja.dato); setCajasDisponibles(disponibles.datos); setProductos(referencias.datos); if (!caja.dato) setModalCaja(true); } catch (error) { setMensaje(error.message); } }, [token]);
  useEffect(() => { cargar(); }, [cargar]);
  const resultados = useMemo(() => { const termino = buscar.trim().toLocaleLowerCase('es'); if (termino.length < 2) return []; return productos.filter((producto) => Number(producto.stock) > 0 && (`${producto.nombre} ${producto.codigo_barra}`).toLocaleLowerCase('es').includes(termino)).slice(0, 12); }, [buscar, productos]);
  const total = carrito.reduce((suma, item) => suma + Number(item.cantidad) * Number(item.precio_venta), 0);
  const vuelto = medio === 'efectivo' ? Math.max(0, Number(recibido || 0) - total) : 0;

  function agregar(producto) { setCarrito((actual) => { const existente = actual.find((item) => item.id === producto.id); if (existente) return actual.map((item) => item.id === producto.id ? { ...item, cantidad: Math.min(Number(item.stock), Number(item.cantidad) + 1) } : item); return [...actual, { ...producto, cantidad: 1 }]; }); setBuscar(''); }
  function cambiarCantidad(id, cantidad) { setCarrito((actual) => actual.map((item) => item.id === id ? { ...item, cantidad } : item)); }
  async function abrirCaja(evento) { evento.preventDefault(); const formulario = new FormData(evento.currentTarget); setProcesando(true); try { await pedir('/api/ventas/caja/abrir', token, { method: 'POST', body: JSON.stringify({ caja_id: Number(formulario.get('caja_id')), monto_inicial: Number(formulario.get('monto_inicial')) }) }); setModalCaja(false); setMensaje('Caja abierta correctamente.'); await cargar(); } catch (error) { setMensaje(error.message); await cargar(); } finally { setProcesando(false); } }
  async function cobrar() { setProcesando(true); try { const respuesta = await pedir('/api/ventas', token, { method: 'POST', body: JSON.stringify({ detalles: carrito.map((item) => ({ producto_id: item.id, cantidad: Number(item.cantidad) })), pagos: [{ medio, monto: total }] }) }); setModalCobro(false); setCarrito([]); setRecibido(''); setMensaje(`Venta #${respuesta.dato.id} registrada correctamente.`); await cargar(); } catch (error) { setMensaje(error.message); } finally { setProcesando(false); } }

  return <section className="modulo modulo-ventas"><div className="modulo__encabezado"><div><p className="etiqueta">PUNTO DE VENTA</p><h2>Nueva venta</h2></div><div className="caja-actual">{sesion ? <><span>{sesion.caja}</span><small>Abierta {new Date(sesion.fecha_apertura).toLocaleTimeString('es-AR', { hour: '2-digit', minute: '2-digit' })}</small></> : <button className="boton" onClick={() => setModalCaja(true)}>Abrir caja</button>}</div></div>{mensaje && <p className="mensaje">{mensaje}</p>}
    <div className="rejilla-venta"><article className="panel buscador-venta"><h3>Agregar productos</h3><input value={buscar} onChange={(evento) => setBuscar(evento.target.value)} placeholder="Escaneá o buscá por nombre o código" autoFocus />{resultados.length > 0 && <div className="resultados-venta">{resultados.map((producto) => <button type="button" key={producto.id} onClick={() => agregar(producto)}><span>{producto.nombre}</span><small>{producto.codigo_barra} · Stock {Number(producto.stock).toLocaleString('es-AR')}</small><strong>${Number(producto.precio_venta).toLocaleString('es-AR', { minimumFractionDigits: 2 })}</strong></button>)}</div>}</article>
      <article className="panel panel-carrito"><div className="panel__encabezado"><h3>Productos</h3><span>{carrito.length} artículos</span></div>{carrito.length ? <div className="tabla-contenedor tabla-carrito"><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio</th><th>Subtotal</th><th></th></tr></thead><tbody>{carrito.map((item) => <tr key={item.id}><td>{item.nombre}<small className="dato-secundario">Stock: {Number(item.stock).toLocaleString('es-AR')}</small></td><td><input type="number" min={item.es_pesable ? '0.001' : '1'} max={item.stock} step={item.es_pesable ? '0.001' : '1'} value={item.cantidad} onFocus={(evento) => evento.currentTarget.select()} onChange={(evento) => cambiarCantidad(item.id, evento.target.value)} /></td><td>${Number(item.precio_venta).toLocaleString('es-AR', { minimumFractionDigits: 2 })}</td><td>${(Number(item.cantidad) * Number(item.precio_venta)).toLocaleString('es-AR', { minimumFractionDigits: 2 })}</td><td><button className="boton-tabla" onClick={() => setCarrito((actual) => actual.filter((otro) => otro.id !== item.id))}>Quitar</button></td></tr>)}</tbody></table></div> : <p className="vacio">Todavía no agregaste productos.</p>}<div className="pie-venta"><span>Total</span><strong>${total.toLocaleString('es-AR', { minimumFractionDigits: 2 })}</strong><button className="boton" disabled={!sesion || !carrito.length} onClick={() => { setRecibido(String(total)); setModalCobro(true); }}>Cobrar</button></div></article></div>
    <Modal abierto={modalCaja} titulo="Abrir caja" alCerrar={() => { if (sesion) setModalCaja(false); }}><form className="formulario-modal" onSubmit={abrirCaja}><p>Seleccioná una caja libre e ingresá el efectivo disponible al comenzar el turno.</p>{cajasDisponibles.length ? <><div><label htmlFor="caja_id">Caja</label><select id="caja_id" name="caja_id" required defaultValue=""><option value="" disabled>Seleccionar caja disponible</option>{cajasDisponibles.map((caja) => <option key={caja.id} value={caja.id}>{caja.nombre}</option>)}</select></div><div><label htmlFor="monto_inicial">Monto inicial</label><input id="monto_inicial" name="monto_inicial" type="number" min="0" step="0.01" defaultValue="0" onFocus={(evento) => evento.currentTarget.select()} required /></div></> : <p className="mensaje-error">No hay cajas disponibles. Debe cerrarse una sesión antes de abrir otra.</p>}<div className="modal__acciones"><button className="boton" disabled={procesando || !cajasDisponibles.length}>{procesando ? 'Abriendo…' : 'Abrir caja'}</button></div></form></Modal>
    <Modal abierto={modalCobro} titulo="Confirmar cobro" alCerrar={() => { if (!procesando) setModalCobro(false); }}><div className="formulario-modal"><p className="importe-cobro">Total a cobrar <strong>${total.toLocaleString('es-AR', { minimumFractionDigits: 2 })}</strong></p><div><label htmlFor="medio_pago">Medio de pago</label><select id="medio_pago" value={medio} onChange={(evento) => setMedio(evento.target.value)}><option value="efectivo">Efectivo</option><option value="debito">Débito</option><option value="credito">Crédito</option><option value="transferencia">Transferencia</option></select></div>{medio === 'efectivo' && <><div><label htmlFor="importe_recibido">Importe recibido</label><input id="importe_recibido" type="number" min={total} step="0.01" value={recibido} onFocus={(evento) => evento.currentTarget.select()} onChange={(evento) => setRecibido(evento.target.value)} /></div><p>Vuelto: <strong>${vuelto.toLocaleString('es-AR', { minimumFractionDigits: 2 })}</strong></p></>}<div className="modal__acciones"><button className="boton boton--secundario" disabled={procesando} onClick={() => setModalCobro(false)}>Cancelar</button><button className="boton" disabled={procesando || (medio === 'efectivo' && Number(recibido) < total)} onClick={cobrar}>{procesando ? 'Registrando…' : 'Confirmar venta'}</button></div></div></Modal>
  </section>;
}
