import { Router } from 'express';
import { requerirAutenticacion } from '../seguridad/autenticacion.middleware.js';
import { requerirPermiso } from '../seguridad/permisos.middleware.js';
import { esquemaAnularGasto, esquemaCategoriaGasto, esquemaConsultaGastos, esquemaGasto, esquemaIdGasto, esquemaPagoGasto } from './gastos.esquemas.js';
import { anularGasto, crearCategoriaGasto, crearGasto, detalleGasto, editarGasto, listarGastos, pagarGasto, referenciasGastos, renovarGasto } from './gastos.servicio.js';

export const rutasGastos = Router();
rutasGastos.use(requerirAutenticacion);
rutasGastos.get('/referencias', requerirPermiso('gastos.ver'), async (_q, r) => r.json(await referenciasGastos()));
rutasGastos.get('/', requerirPermiso('gastos.ver'), async (q, r) => { const v = esquemaConsultaGastos.safeParse(q.query); if (!v.success) return r.status(400).json({ mensaje: 'Consulta inválida' }); r.json(await listarGastos(v.data)); });
rutasGastos.post('/categorias', requerirPermiso('gastos.gestionar'), async (q, r) => { const v = esquemaCategoriaGasto.safeParse(q.body); if (!v.success) return r.status(400).json({ mensaje: 'Categoría inválida' }); r.status(201).json({ dato: await crearCategoriaGasto(v.data.nombre) }); });
rutasGastos.post('/', requerirPermiso('gastos.gestionar'), async (q, r) => { const v = esquemaGasto.safeParse(q.body); if (!v.success) return r.status(400).json({ mensaje: 'Datos de gasto inválidos' }); r.status(201).json({ dato: await crearGasto(v.data, q.usuario.id) }); });
rutasGastos.put('/:id', requerirPermiso('gastos.gestionar'), async (q, r) => { const id = esquemaIdGasto.safeParse(q.params.id); const v = esquemaGasto.safeParse(q.body); if (!id.success || !v.success) return r.status(400).json({ mensaje: 'Datos de gasto inválidos' }); try { r.json({ dato: await editarGasto(id.data, v.data) }); } catch (e) { if (e.codigoPublico) return r.status(409).json({ mensaje: e.message }); throw e; } });
rutasGastos.get('/:id', requerirPermiso('gastos.ver'), async (q, r) => { const id = esquemaIdGasto.safeParse(q.params.id); if (!id.success) return r.status(400).json({ mensaje: 'Gasto inválido' }); const dato = await detalleGasto(id.data); if (!dato) return r.status(404).json({ mensaje: 'No se encontró el gasto' }); r.json({ dato }); });
rutasGastos.post('/:id/pagos', requerirPermiso('gastos.gestionar'), async (q, r) => { const id = esquemaIdGasto.safeParse(q.params.id); const v = esquemaPagoGasto.safeParse(q.body); if (!id.success || !v.success) return r.status(400).json({ mensaje: 'Pago inválido' }); try { r.status(201).json({ dato: await pagarGasto(id.data, q.usuario.id, v.data) }); } catch (e) { if (e.codigoPublico) return r.status(409).json({ mensaje: e.message }); throw e; } });
rutasGastos.post('/:id/renovar', requerirPermiso('gastos.gestionar'), async (q, r) => { const id = esquemaIdGasto.safeParse(q.params.id); const v = esquemaGasto.safeParse(q.body); if (!id.success || !v.success) return r.status(400).json({ mensaje: 'Datos del próximo período inválidos' }); try { r.status(201).json({ dato: await renovarGasto(id.data, q.usuario.id, v.data) }); } catch (e) { if (e.codigoPublico) return r.status(409).json({ mensaje: e.message }); throw e; } });
rutasGastos.post('/:id/anular', requerirPermiso('gastos.gestionar'), async (q, r) => { const id = esquemaIdGasto.safeParse(q.params.id); const v = esquemaAnularGasto.safeParse(q.body); if (!id.success || !v.success) return r.status(400).json({ mensaje: 'Motivo de anulación inválido' }); try { r.json({ dato: await anularGasto(id.data, q.usuario.id, v.data.motivo) }); } catch (e) { if (e.codigoPublico) return r.status(409).json({ mensaje: e.message }); throw e; } });
